config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#top'
  get '/home/about' => 'home#about'
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  attachment :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to books_path
  end



  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new

  end

  def index

  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)  
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<main>
  <h2>User Info</h2>
    <%= attachment_image_tag user, :profile_image_id, :fill, 60, 60, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
	          <th>name</th>
	          <th><%= user.name %></th>
          </tr>
          <tr>
	          <th>introduction</th>
	          <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
        <div class="row">
          <%= link_to  edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog edit_user_4043"></i>
          <% end %>
        </div>
        <h2 class="mt-3">New Book</h2>
          <%= form_with model: new_book, local:true do |f| %>
            <label>Title</label>
              <%= f.text_field :title, class: "form-control" %>
            <label>Opinion</label>
              <%= f.text_area :body, class: "form-control" %>
            <div class="button"><%= f.submit 'Create Book', class: "btn btn-success"%></div>
          <% end %>
  </main>

app/views/books/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', new_book: @new_book, user: @book.user %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
              <tr>
                <td>
                  <%= link_to user_path(@book.user.id) do %>
                  <%= attachment_image_tag @book.user, :profile_image_id, :fill, 60, 60, fallback: "no_image_2.jpg" %>
                  <% end %>
                  <div><%= link_to @book.user.name, user_path(@book.user.id) %></div>
                </td>
                <td><%= link_to @book.title, book_path(@book.id)%></td>
                <td><%= @book.body %></td>
                <td><%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-sm btn-success edit_book_4080' %></td>
                <td>
                  <%= link_to "Destroy", book_path(@book.id), method: :delete, class: 'btn btn-sm btn-danger destroy_book_4080' ,"data-confirm" => "本当に消しますか？"%>
                </td>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/home/about.html.erb
<main>
  <p id="notice"></p>
    <div class="container">
      <div class="row">
       <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
      </div>
    </div>
</main>

app/views/home/top.html.erb
<main>
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2Review</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/788e1bc3ee.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/"><span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
              <%= link_to "Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
              </li>
              <li class="nav-item">
              <%= link_to "Users", users_path, class: 'fas fa-users nav-link text-light' %>
              </li>
              <li class="nav-item">
              <%= link_to "Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>

            　<% else %>
            <li class="nav-item">
              <%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "About", home_about_path, class: 'fas fa-link nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
            <% end %>
            </ul>
          </div>
      </div>
    </nav>
  </header>
    <%= yield %>
    <footer>
      <div class="container mt-5">
  	    <div class="row">
    	    <div class="mx-auto">
    		   <p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

  </body>
</html>

app/views/users/edit.html.erb
<main>
    <p id="notice"></p>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h2>User info</h2>
              <%= form_with model: @user, local:true do |f| %>
                <label>Name</label>
                 <%= f.text_field :name, class: "form-control" %>
                 <label>Image</label>
                 <input class="form-control-file user_image" data-reference="0d51371edc108d9b4703af9ea9c6e53b" include_hidden="false" type="file" name="user[profile_image]" id="user_profile_image">
                 <label>Introduction</label>
                 <%= f.text_area :introduction, class: "form-control" %>
                <div class="button"><%= f.submit 'Update User', class: "btn btn-secondary"%></div>
              <% end %>
          </div>
        </div>
      </div>
  </main>

app/views/users/show.html.erb
<main>
<p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'books/list', new_book: @new_book, user: @user %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
          <table class="table">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
	              <th>Opinion</th>
	              <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image_id, :fill, 60, 60, fallback: "no_image_2.jpg" %>
                  <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id)%></td>
                <td><%= book.body %></td>
                <% end %>
              </tr>
            </tbody>
          </table>
      </div>
    </div>
  </div>
</main>